name: coolicons
description: The Coolicons icon pack for Flutter with over 400 icons available for your flutter project.
version: 1.0.0
repository: https://github.com/Mastersam07/coolicons
homepage: https://github.com/Mastersam07/coolicons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: coolicons
      fonts:
        - asset: fonts/coolicons.ttf